config/routes.rb
OnCallAid::Application.routes.draw do

  HOSTNAME = 'network.thewellinspired.com' + (Rails.env.production? ? '' : '.dev')

  ## Stub out routes for forwarding on to the Inspired Network.
  ## Need to hit the Rack session directly as our router doesn't have any idea about our application.
  get '/users/sign_in' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signin'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_session

  get '/users/sign_up' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signup'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_registration

  get '/auth/:action/callback' => 'omniauth#:action', :as => :omniauth_callback
  get '/auth/failure' => 'omniauth#failure', :as => :omniauth_failure

  delete '/users/sign_out' => redirect { |p, r|
    r.session[:user_id] = nil
    r.flash[:notice] = "Successfully signed you out."
    "#{r.scheme}://#{HOSTNAME}/users/sign_out?redirect_to=#{r.referer || '/'}"
  }, :as => :destroy_session

  resources :users, :only => [ :show ]

  controller :public do
    get :attribution
    get :contributors
    get :disclaimer
    get :ios
  end

  get 'feedback', :to => 'feedback#new', :as => 'feedback'
  post 'feedback', :to => 'feedback#create'

  resources :chapters, :only => [ :show ]
  # We still want the #show action on articles so we can redirect to the slug path.
  resources :articles do
    collection do
      get :xml
    end
  end
  resources :submissions do
    member do
      get    :moderate
      put    :accept
      delete :reject
    end
  end
  # Needs to go last as it's a catch-all...
  get ':chapter_slug/:slug' => 'articles#show', :as => :slug, :constraints => { :format => 'html' }

  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :chapter, :touch => true

  has_paper_trail :class_name => 'ArticleVersion'

  has_many :contributions
  has_many :submissions

  attr_accessible :title, :body, :chapter_id

  validates_uniqueness_of :slug, :scope => [ :chapter_id ]
  validates_length_of :title, :minimum => 1
  validates_uniqueness_of :title

  default_scope -> { where(:deleted => false).order(:sort_title) }

  before_save :update_slug
  before_save :update_sort_title
  before_save :clean_newlines
  before_save :update_empty

  def contribution_counts
    c = self.contributions.order('SUM(contributions.word_size) DESC').select('contributions.*, SUM(contributions.word_size) AS word_count, SUM(contributions.line_size) AS line_count').having('SUM(contributions.word_size) > 0').includes(:user).group(all_columns(:contributions))
    require 'ostruct'
    c.collect do |c|
      OpenStruct.new({
        :user => c.user,
        :word_count => c.word_count.to_i,
        :line_count => c.line_count.to_i
      })
    end
  end

  private

  def update_empty
    self.empty = self.body.nil? || self.body.empty? || self.body.length < 10
    return true
  end

  def update_slug
    self.slug = self.title.parameterize if self.title_changed?
    return true
  end

  def update_sort_title
    self.sort_title = self.title.gsub(/^(the|a|an)\s/i,'') if self.title_changed?
    return true
  end

  def clean_newlines
    self.body.gsub!(/\r\n?/,"\n") rescue nil
    return true
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # etag { current_user.try(:id) }

  def index
    @chapters = Chapter.all
    # fresh_when(@chapters.map(&:articles))
  end

  def show
    begin
      @article = Article.where(:slug => params[:slug]).first!
      @user_submission_scope = @article.submissions.not_accepted.where(:user_id => current_user.id)
      fresh_when(@article)
    rescue ActiveRecord::RecordNotFound
      if @article = Article.where(:id => params[:id]).first
        return redirect_to slug_path(:chapter_slug => @article.chapter.slug, :slug => @article.slug)
      else
        return head :not_found
      end
    end
  end

  def new
    # Dead links in article copy are linked to new article with a 'title' param.
    params[:article] ||= {}
    title = params[:article][:title] || params[:title]
    @article = Article.new(params[:article].merge(:title => title))
    authorize! :create, @article
    render :edit
  end

  # Redirect to new submission unless we're an admin or moderator.
  def edit
    begin
      @article = Article.where(:id => params[:id]).first!
      if cannot? :update, @article
        @submission = @article.submissions.new(:body => @article.body)
        authorize! :create, @submission
        session[:new_submission_article_id] = @submission.article_id
        return redirect_to new_submission_path
      end
    rescue ActiveRecord::RecordNotFound
      return head :not_found
    end
  end

  def create
    begin
      authorize! :create, Article.new
      @article = Article.create!(params[:article])
      redirect_to edit_article_path(@article)
    rescue ActiveRecord::RecordInvalid
      render :edit
    end
  end

  def update
    begin
      @article = Article.where(:id => params[:id]).first!
      authorize! :update, @article
    rescue ActiveRecord::RecordNotFound
      return head :not_found
    end
    Article.paper_trail_off if @article.originator == current_user.id.to_s
    if @article.update_attributes(params[:article])
      redirect_to edit_article_path(@article), :notice => 'Article saved!'
    else
      redirect_to edit_article_path(@article), :alert => 'Article invalid.'
    end
  end

  def xml
    authorize! :manage, Article.new if Rails.env.production?
    render :xml => Chapter.all.to_xml(:include => :articles)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def link_to_edit_submission(s)
    link_text = 'Contribute'
    link_text = 'Submission Rejected' if s.rejected.count > 0
    link_text = 'Submission Pending' if s.pending.count > 0
    link_to(link_text, edit_article_path(@article), :class => 'action-link button has-tipsy', :'data-tipsy-text' => 'Have a correction or addition to make? Click here to sign in!')
  end

end

app/views/articles/edit.html.erb
<div class="edit article">

	<% if @article.persisted? %>
		<p>This article has <%= @article.submissions.pending.count %> submissions pending approval. <%= link_to('View article', slug_path(:chapter_slug => @article.chapter.slug, :slug => @article.slug), :target => '_blank') %>.</p>
	<% end %>

	<%= form_for(@article) do |f| %>
		<label for="title">Title:</label>
		<%= f.text_field :title %>

		<label for="content">Content:</label>
		<%= f.text_area :body %>

		<label for="chapter_id">Select Chapter:</label>
		<%= f.select :chapter_id, Chapter.all.collect {|p| [ p.title, p.id ] } %>

		<%= f.submit %>
	<% end %>
</div>

app/views/articles/index.html.erb
<article id="toc">
	<% @chapters.each do |c| %>
		<table class="toc">
			<tr>
				<th colspan="3"><%= c.title %></th>
			</tr>
			<% c.articles.in_groups_of(3) do |row| %>
			<tr>
				<% row.each do |article| %>
				<td><%= article.nil? ? '' : link_to(article.title, slug_path(:chapter_slug => c.slug, :slug => article.slug), :class => (article.body.empty? ? 'empty' : '')) %></td>
				<% end %>
			</tr>
			<% end %>
		</table>
	<% end %>
	<%= link_to('Suggest a New Topic!', 'mailto:article-suggestions@thewellinspired.com', :class => 'action-link') if cannot?(:create, Article.new) %>
	<%= link_to('new article', new_article_path, :class => 'action-link') if can?(:create, Article.new) %>
	<div class="ios-ad">
		Get it on your iPhone or iPad.
	</div>
	<script type="text/javascript">
	OCA.queue.wait(function() {
		$(function() {
			$('.ios-ad').click(function() {
				location.href = '<%= ios_path %>';
			});
		})
	});
	</script>
</article>

app/views/articles/show.html.erb
<article>
	<div class="action-links">
		<% if can?(:update, @article) %>
		<%= link_to('edit', edit_article_path(@article), :class => 'action-link button') %>
		<% else %>
		<%= link_to_edit_submission(@user_submission_scope) %>
		<% end %>
	</div>
	<header><%= @article.title %></header>
	<% a = markdown(@article.body) %>
	<% if a.length > 1 %>
		<%= a %>
	<% else %>
		<p>
			Help your colleagues out and <%= link_to('start', edit_article_path(@article)) %> this article off!
		</p>
	<% end %>
	<% contributions = @article.contribution_counts %>
	<% if contributions.length > 0 %>
	<div class="show-contributors"><%= pluralize(contributions.length, 'contribution') %> to this article by <%= pluralize(contributions.map{ |c| c.user }.uniq.length, 'user') %> &#9660;</div>
	<ul class="contributors" style="display: none;">
	<% contributions.each do |c| %>
		<li>
			<% if c.user.profile %>
				<%= image_tag(c.user.gravatar_url(:size => 60), :width => 30, :height => 30) %><span class="title"><%= c.user.profile.title %> </span><span class="name"><%= c.user.profile.name %></span> <span class="postnominals"><%= c.user.profile.postnominals %></span>
				<div class="contributions">
					Contributions to this article: <span class="word-total"><%= c.word_count %></span> words
				</div>
			<% else %>
				<%= image_tag(c.user.gravatar_url(:size => 60), :width => 30, :height => 30) %><span class="name"><%= c.user.username %></span>
				<div class="contributions">
					Contributions to this article: <span class="word-total"><%= c.word_count %></span> words
				</div>
			<% end %>
		</li>
	<% end %>
	</ul>
	<% end %>
	<div class="ios-ad">
		Get it on your iPhone or iPad.
	</div>
	<script type="text/javascript">
	OCA.queue.wait(function() {
		$(function() {
			$('.ios-ad').click(function() {
				location.href = '<%= ios_path %>';
			});
			$('.show-contributors').click(function() {
				$('.contributors').toggle();
			});
		})
	});
	</script>
</article>