config/routes.rb
OnCallAid::Application.routes.draw do

  HOSTNAME = 'network.thewellinspired.com' + (Rails.env.production? ? '' : '.dev')

  ## Stub out routes for forwarding on to the Inspired Network.
  ## Need to hit the Rack session directly as our router doesn't have any idea about our application.
  get '/users/sign_in' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signin'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_session

  get '/users/sign_up' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signup'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_registration

  get '/auth/:action/callback' => 'omniauth#:action', :as => :omniauth_callback
  get '/auth/failure' => 'omniauth#failure', :as => :omniauth_failure

  delete '/users/sign_out' => redirect { |p, r|
    r.session[:user_id] = nil
    r.flash[:notice] = "Successfully signed you out."
    "#{r.scheme}://#{HOSTNAME}/users/sign_out?redirect_to=#{r.referer || '/'}"
  }, :as => :destroy_session

  resources :users, :only => [ :show ]

  controller :public do
    get :attribution
    get :contributors
    get :disclaimer
    get :ios
  end

  get 'feedback', :to => 'feedback#new', :as => 'feedback'
  post 'feedback', :to => 'feedback#create'

  resources :chapters, :only => [ :show ]
  # We still want the #show action on articles so we can redirect to the slug path.
  resources :articles do
    collection do
      get :xml
    end
  end
  resources :submissions do
    member do
      get    :moderate
      put    :accept
      delete :reject
    end
  end
  # Needs to go last as it's a catch-all...
  get ':chapter_slug/:slug' => 'articles#show', :as => :slug, :constraints => { :format => 'html' }

  root :to => 'articles#index'
end

app/models/submission.rb
class Submission < ActiveRecord::Base

  belongs_to :article
  belongs_to :user

  # Title isn't accessible as we set it automatically to match the article's title.
  attr_accessible :body

  validates_presence_of :user
  validates_length_of :title, :minimum => 1
  validates_length_of :body, :minimum => 1, :message => 'Your edit is too short.'
  validates_uniqueness_of :body, :scope => :user_id, :message => "Oops, looks like you've already submitted this edit!"

  validate :must_be_different, :on => :create
  validates :status, :inclusion => { :in => %w(pending rejected accepted) }

  after_initialize :pull_article_data

  scope :pending, -> { where(:status => 'pending') }
  scope :rejected, -> { where(:status => 'rejected') }
  scope :accepted, -> { where(:status => 'accepted') }
  scope :not_accepted, -> { where(%|submissions.status != 'accepted'|) }

  def must_be_different
    errors.add(:body, "You haven't made any changes.") if self.body == self.article.body
  end

  def accept!
    w = PaperTrail.whodunnit
    PaperTrail.whodunnit = self.user
    Article.paper_trail_off if self.article.originator == self.user.to_s
    self.article.update_attributes!({
      :title => self.title,
      :body => self.body
    })
    PaperTrail.whodunnit = w
    self.status = 'accepted'
    self.save!
    SubmissionMailer.notify_accepted(self.id).deliver
  end

  def reject!
    self.status = 'rejected'
    self.save!
    SubmissionMailer.notify_rejected(self.id).deliver
  end

  private

  def pull_article_data
    self.title = self.article.title
    self.body ||= self.article.body
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def new
    # Show errors as flash messages. Maybe change this to inline later?
    #flash[:alert]
    return redirect_back_or unless session[:new_submission_article_id]
    @article = Article.where(:id => session[:new_submission_article_id]).first!
    @submission = @article.submissions.not_accepted.where(:user_id => current_user.id).first_or_initialize
    @submission.assign_attributes(params[:submission])
    return redirect_to edit_submission_path(@submission) if @submission.persisted?
  end

  def create
    @article = Article.where(:id => session[:new_submission_article_id]).first!
    @submission = @article.submissions.new(params[:submission])
    @submission.user = current_user
    if @submission.save
      session[:new_submission_article_id] = nil
      SubmissionMailer.new_submission(@submission.id).deliver
      redirect_to slug_path(:chapter_slug => @article.chapter.slug, :slug => @article.slug), :notice => 'Thanks, submission saved!'
    else
      flash[:alert] = @submission.errors.messages.values.join(' ')
      render :new
    end
  end

  def edit
    @submission = current_user.submissions.where(:id => params[:id]).first!
    @article = @submission.article
    render :new
  end

  def update
    @submission = current_user.submissions.where(:id => params[:id]).first!
    params[:submission] = params[:submission].slice(:body).merge({
      :rejected_reason => nil,
      :status => 'pending'
    })
    if @submission.update_attributes(params[:submission], :without_protection => true)
      session[:new_submission_article_id] = nil
      redirect_to slug_path(:chapter_slug => @submission.article.chapter.slug, :slug => @submission.article.slug), :notice => 'Thanks, submission updated!'
    else
      flash[:alert] = @submission.errors.messages.values.join(' ')
      render :new
    end
  end

  def moderate
    @submission = Submission.where(:id => params[:id]).first!
    authorize! :update, @submission.article
  end

  def accept
    @submission = Submission.where(:id => params[:id]).first!
    authorize! :update, @submission.article
    @submission.update_attributes!(params[:submission])
    @submission.accept!
    redirect_to slug_path(:chapter_slug => @submission.article.chapter.slug, :slug => @submission.article.slug), :notice => 'Submission accepted!'
  end

  def reject
    @submission = Submission.where(:id => params[:id]).first!
    authorize! :update, @submission.article
    # For saving the rejected_reason.
    @submission.update_attributes(params[:submission])
    @submission.reject!
    redirect_to slug_path(:chapter_slug => @submission.article.chapter.slug, :slug => @submission.article.slug), :notice => 'Submission rejected.'
  end

  def destroy
    @submission = current_user.submissions.where(:id => params[:id]).first!
    article = @submission.article
    @submission.destroy
    redirect_to slug_path(:chapter_slug => article.chapter.slug, :slug => article.slug), :notice => 'Submission deleted.'
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/moderate.html.erb
<div class="moderate submission">

	<header>Moderating: <%= @submission.article.title %></header>

	<p>This submission was contributed by <strong><%= @submission.user.username %></strong> (<%= mail_to(@submission.user.email) %>) <%= time_ago_in_words(@submission.updated_at) %> ago.</p>

	<%= form_for(@submission, :url => accept_submission_path(@submission)) do |f| %>

		<label for="body"><span class="markdown-explanation">(you can use <span style="border-bottom: 1px dotted #666;">Markdown</span> for formatting)</span></label>
		<%= f.text_area :body %>

		<%= f.submit "Accept this submission" %>
	<% end %>

	<%= form_for(@submission, :url => reject_submission_path(@submission), :method => :delete) do |f| %>

		<label for="rejected_reason">Reason why you're rejecting this submission:</label>
		<%= f.text_area :rejected_reason, :rows => 5 %>

		<%= f.submit "Reject this submission" %>
	<% end %>

	<%= render :partial => 'helpbox' %>
</div>

app/views/submissions/new.html.erb
<div class="new submission">

	<header>Editing: <%= @article.title %></header>

	<p>Thanks for contributing! You can edit <strong>&ldquo;<%= @article.title %>&rdquo;</strong> below to your heart's content, and when you're done your submission will be reviewed by editorial staff before going live on the site.</p>

	<% if @submission.persisted? %>
	<p>Your current submission for this article is still pending moderation, but feel free to edit and re-submit below.</p>
	<% elsif @submission.rejected_reason.present? %>
	<p>Your current submission for this article has been rejected with the following explanation: "<%= @submission.rejected_reason %>". Please feel free to edit this submission, or delete it and restart from scratch &mdash; we'd love to have your contributions!</p>
	<% end %>

	<%= form_for(@submission) do |f| %>

		<label for="content"><span class="markdown-explanation">(you can use <span style="border-bottom: 1px dotted #666;">Markdown</span> for formatting)</span></label>
		<%= f.text_area :body %>

		<%= f.submit "Fire away!" %>
		<%= link_to('Delete this submission', submission_path(@submission), :method => :delete) if @submission.persisted? %>
	<% end %>

	<%= render :partial => 'helpbox' %>
</div>