config/routes.rb
OnCallAid::Application.routes.draw do

  HOSTNAME = 'network.thewellinspired.com' + (Rails.env.production? ? '' : '.dev')

  ## Stub out routes for forwarding on to the Inspired Network.
  ## Need to hit the Rack session directly as our router doesn't have any idea about our application.
  get '/users/sign_in' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signin'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_session

  get '/users/sign_up' => redirect { |p, r|
    # We may have already set the referrer from CanCan::AccessDenied
    r.session[:referrer] ||= r.referrer
    r.session[:type] = 'signup'
    r.session[:message] = r.flash[:alert] || r.flash[:notice]
    r.flash[:alert] = r.flash[:notice] = nil
    '/auth/the_inspired_network'
  }, :as => :new_registration

  get '/auth/:action/callback' => 'omniauth#:action', :as => :omniauth_callback
  get '/auth/failure' => 'omniauth#failure', :as => :omniauth_failure

  delete '/users/sign_out' => redirect { |p, r|
    r.session[:user_id] = nil
    r.flash[:notice] = "Successfully signed you out."
    "#{r.scheme}://#{HOSTNAME}/users/sign_out?redirect_to=#{r.referer || '/'}"
  }, :as => :destroy_session

  resources :users, :only => [ :show ]

  controller :public do
    get :attribution
    get :contributors
    get :disclaimer
    get :ios
  end

  get 'feedback', :to => 'feedback#new', :as => 'feedback'
  post 'feedback', :to => 'feedback#create'

  resources :chapters, :only => [ :show ]
  # We still want the #show action on articles so we can redirect to the slug path.
  resources :articles do
    collection do
      get :xml
    end
  end
  resources :submissions do
    member do
      get    :moderate
      put    :accept
      delete :reject
    end
  end
  # Needs to go last as it's a catch-all...
  get ':chapter_slug/:slug' => 'articles#show', :as => :slug, :constraints => { :format => 'html' }

  root :to => 'articles#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  include OCAMarkdown

  helper :all

  helper_method :current_user

  layout :set_layout

  def current_user
    session[:user_id] = User.first.id if Rails.env.development?
    User.where(:id => session[:user_id]).first || User.new(:username => 'Guest')
  end

  # This method is used by the PaperTrail gem to store the user responsible for a model update.
  def user_for_paper_trail
    current_user.persisted? ? current_user : nil
  end

  # Extra information to store with each version.
  def info_for_paper_trail
    { :ip => request.remote_ip }
  end

  def local_request?
    local_addresses = ['127.0.0.1', '::1']
    (local_addresses.include?(request.remote_addr) && local_addresses.include?(request.remote_ip)) || Rails.env.development?
  end

  def redirect_back_or(default = nil, options = {})
    begin
      redirect_to(:back, options)
    rescue ActionController::RedirectBackError
      redirect_to(default || studies_path, options)
    end
  end

  def redirect_unless_logged_in
    raise CanCan::AccessDenied unless current_user && current_user.persisted?
  end

  private

  def set_layout
    request.xhr? ? nil : 'application'
  end

  rescue_from CanCan::AccessDenied do |e|
    logger.info('CanCan::AccessDenied') if Rails.env.development? || Rails.env.staging?
    if current_user.persisted?
      respond_to do |wants|
        wants.html { redirect_back_or root_path, :alert => "Sorry, but you don't have access to that." }
        wants.any { head :forbidden }
      end
    else
      session[:referrer] = request.url
      redirect_to new_session_path, :alert => "Please sign in or sign up to contribute to OnCallAid."
    end
  end

  rescue_from TWI::DuplicateProfileError, TWI::DuplicateEmailError do |e|
    redirect_back_or root_path, :alert => e.message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = nil)
    title ||= @article && @article.title
    title.blank? ? "OnCallAid" : "#{title} &mdash; OnCallAid".html_safe
  end

  def google(ua_code = 'UA-3289741-36')
    raw(%Q[<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', '#{ua_code}', 'auto');ga('send', 'pageview');</script>])
  end

end

app/views/application/_footer.html.erb
<div id="footer-container">
	<div id="footer">
		<div class="row">
			<div class="cell left">
				<%= link_to('Give Us Feedback!', feedback_path) if can?(:send, :feedback) %>
				<%= link_to('Contributors', contributors_path) %>
				<%= link_to('Disclaimer', disclaimer_path, :rel => 'facebox') %>
			</div>
			<div class="cell">
				<h2>The Inspired Network</h2>
				OnCallAid
			</div>
			<div class="cell">
				<h2>The Instigators</h2>
				<div class="instigators">
					site design &amp; logo &copy; <%= Time.now.year %> <%= link_to('The Well Inspired Ventures, Inc.', 'http://thewellinspired.com')%><br>
					user contributions licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">CC BY-NC-SA 3.0</a> with <%= link_to('attribution required', attribution_path) %>.
					<br>
					Get OnCallAid <%= link_to('On your iPhone or iPad', ios_path) %>.<br>
					<%= link_to('A Production of The Well Inspired Ventures, Inc.', 'http://thewellinspired.com/', :class => 'logo') %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/application/_header.html.erb
<div id="header-container">
	<div id="header">
		<h1><%= link_to(provide(:page_title), root_path) %></h1>

		<% if current_user.persisted? %>

		<div class="rep-tag-header">
			<%= render :partial => 'rep_tag', :locals => { :user => current_user } %>
			<div class="buttons">
				<%= link_to('Sign out', destroy_session_path, :method => :delete) %>
			</div>
		</div>

		<% else %>

		<div class="public-links">
			<%= link_to('Sign up', new_registration_path) %> |
			<%= link_to('Sign in', new_session_path, :class => 'green') %>
		</div>

		<% end %>

		<div class="twi-logo">
			<%= link_to('the well inspired ventures, inc.', 'http://thewellinspired.com') %>
		</div>
	</div>
</div>

<div id="sub-header">
	<h1>A collaborative &amp; concise on call reference for senior medical students and junior doctors.</h1>
</div>

app/views/application/_helpbox.html.erb
<div class="markdown-box">
	<table class="markdown-table">
		<tr>
			<th colspan="2">
				<i class="icon-markdown"></i> Format your submissions using Markdown.
			</th>
		</tr>
		<tr>
			<td>Bold</td>
			<td><strong>**bold**</strong></td>
		</tr>
		<tr>
			<td>Italic</td>
			<td><em>*italic*</em></td>
		</tr>
		<tr>
			<td>Link</td>
			<td>[Link Text](http://example.com/)</td>
		</tr>
		<tr>
			<td>List</td>
			<td>
				<code>* list-element-1<br>
					* list-element-2<br>
					&nbsp;&nbsp;&nbsp;&nbsp;* nested-element-starts-with-4-spaces</code>
			</td>
		</tr>
		<tr><td colspan="2">
		<%= link_to('More on Markdown', 'http://daringfireball.net/projects/markdown/basics', :target => '_blank') %>
		</td></tr>
	</table>
</div>

app/views/application/_notices.html.erb
<% if alert %>

	<script type="text/javascript">
	OCA.queue.wait(function() {
		$(function() {
			OCA.alert('<%= escape_javascript(alert) %>');
		})
	});
	</script>

<% elsif notice %>

	<script type="text/javascript">
	OCA.queue.wait(function() {
		$(function() {
			OCA.notice('<%= escape_javascript(notice) %>');
		})
	});
	</script>

<% end %>

app/views/application/_rep_tag.html.erb
<% font_size ||= false %>
<%= content_tag(:div, :class => 'rep-tag', :style => (font_size ? "font-size: #{font_size.to_s}px;" : "")) do %>
    <%= image_tag(user.gravatar_url(:size => 44), :class => 'pic', :width => 22, :height => 22) %>
    <div class="name">
        <%= link_to(user.username, profile_url(:id => user.authorizations.first.uid)) %>
    </div>
    <div class="rep">
        <%= user.contribution_counts(:word) %>
    </div>
    <% unless current_user.role == DEFAULT_ROLE %>
        <%= content_tag(:div, :class => [current_user.role, 'badge'].join(' ')) do %>
            <%= current_user.role %>
        <% end %>
    <% end %>
<% end %>